/*Создать представление, которое отобразит средний чек за поездку в разных странах*/
CREATE OR REPLACE VIEW AVG_PAY_TOWAY
AS
SELECT C.NAME
      ,ROUND(AVG(AMOUNT_TO_PAID),2) AVG_PAY_CITY
    FROM CITY C
JOIN COUNTRY CTR
ON C.COUNTRY_ID=CTR.ID
JOIN CURRENCY2COUNTRY C2C
ON CTR.ID = C2C.COUNTRY_ID
JOIN PAYMENT PMNT
ON C2C.CURRENCY_ID = PMNT.CURRENCY_ID
JOIN ORDER1 O
ON PMNT.ID = O.PAYMENT_ID
JOIN WAY
ON O.ID = WAY.ORDER_ID
GROUP BY C.NAME;
/
SELECT * FROM AVG_PAY_TOWAY;